using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace IntegrationService.API.DTOs
{
    /// <summary>
    /// Request to create a scheduled order
    /// </summary>
    public class CreateScheduledOrderRequest
    {
        [Required]
        public int CustomerId { get; set; }

        [Required]
        public DateTime ScheduledDateTime { get; set; }

        [Required]
        [MinLength(1, ErrorMessage = "At least one item is required")]
        public List<ScheduledOrderItemRequest> Items { get; set; }

        // Payment info (from Authorize.net Accept.js)
        [MaxLength(500)]
        public string PaymentAuthorizationNo { get; set; }

        [MaxLength(10)]
        public string PaymentBatchNo { get; set; } = "1";

        public int PaymentTypeId { get; set; } = 3; // Visa default

        public decimal TipAmount { get; set; } = 0;

        [MaxLength(500)]
        public string SpecialInstructions { get; set; }

        // Idempotency key (generated by client)
        [Required]
        [MaxLength(100)]
        public string IdempotencyKey { get; set; }
    }

    public class ScheduledOrderItemRequest
    {
        [Required]
        public int MenuItemId { get; set; }

        [Required]
        public int SizeId { get; set; }

        [Range(1, 100)]
        public int Quantity { get; set; } = 1;

        [Required]
        public decimal UnitPrice { get; set; }

        [MaxLength(200)]
        public string SpecialInstructions { get; set; }
    }

    /// <summary>
    /// Response after creating a scheduled order
    /// </summary>
    public class CreateScheduledOrderResponse
    {
        public bool Success { get; set; }
        public string Message { get; set; }
        public int? ScheduledOrderId { get; set; }
        public string ConfirmationCode { get; set; }
        public DateTime? ScheduledDateTime { get; set; }
        public decimal? TotalAmount { get; set; }
    }

    /// <summary>
    /// Scheduled order details for display
    /// </summary>
    public class ScheduledOrderDto
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public DateTime ScheduledDateTime { get; set; }
        public string Status { get; set; }
        public List<ScheduledOrderItemDto> Items { get; set; }
        public decimal Subtotal { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public string SpecialInstructions { get; set; }
        public string ConfirmationCode { get; set; }
        public DateTime? ReleasedDateTime { get; set; }
        public string PosOrderNumber { get; set; }
        public DateTime CreatedAt { get; set; }
        public bool CanCancel { get; set; }
    }

    public class ScheduledOrderItemDto
    {
        public string ItemName { get; set; }
        public string SizeName { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public string SpecialInstructions { get; set; }
    }

    /// <summary>
    /// Available time slots for a specific date
    /// </summary>
    public class AvailableTimeSlotsResponse
    {
        public DateTime Date { get; set; }
        public List<TimeSlotDto> AvailableSlots { get; set; }
        public string RestaurantOpenTime { get; set; }
        public string RestaurantCloseTime { get; set; }
        public int LeadTimeMinutes { get; set; } = 30; // Minimum time before order
    }

    public class TimeSlotDto
    {
        public string Time { get; set; } // "14:30"
        public string DisplayText { get; set; } // "2:30 PM"
        public bool IsAvailable { get; set; }
    }

    /// <summary>
    /// Request to cancel a scheduled order
    /// </summary>
    public class CancelRequest
    {
        [MaxLength(500)]
        public string? Reason { get; set; }
    }
}
