# Gemfile for iOS Fastlane automation
source "https://rubygems.org"

ruby '>= 3.0.0'

# Fastlane for iOS automation
gem "fastlane", "~> 2.219"

# Plugins
gem "fastlane-plugin-increment_build_number"
gem "fastlane-plugin-versioning"

# Additional tools
gem "cocoapods", "~> 1.14"
