# Resolve react_native_pods.rb with node to allow for hoisting
react_native_pods = Pod::Executable.execute_command('node', ['-p',
  'try { console.log(require.resolve("react-native/scripts/react_native_pods.rb")); } catch (e) { console.log(""); }'
]).strip

if react_native_pods.empty?
  # Fallback to relative path if require.resolve fails (e.g. node_modules not yet populated in the expected way)
  react_native_pods = File.join(__dir__, "..", "node_modules", "react-native", "scripts", "react_native_pods.rb")
end

require react_native_pods

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
target 'ImidusCustomerApp' do
  config = use_native_modules!

  # Flipper is deprecated/removed in RN 0.74+
  flipper_config = defined?(FlipperConfiguration) ? (ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled) : nil

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper if available.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ImidusCustomerAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
