name: Android Build
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  WORKING_DIR: src/mobile/ImidusCustomerApp

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ${{ env.WORKING_DIR }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Release APK
        run: ./gradlew assembleRelease -Pkotlin.warnings.as.errors=false
        working-directory: ${{ env.WORKING_DIR }}/android

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload APK to S3
        run: |
          aws s3 cp app/build/outputs/apk/release/app-release.apk s3://inirestaurant/novatech/mobile/android/ImidusCustomerApp.apk
        working-directory: ${{ env.WORKING_DIR }}/android
